version: '3.9'

services:
    app:
        build: .
        # command: uvicorn main --host 0.0.0.0 --workers 4
        volumes:
            - .:/app
        ports:
            - 8000:8000
        container_name: messaging-back


    